language: java
script: gradle dist

install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: AO0Gn5joVkJ2d71ffauQtG3MGk+Cea5faEFMVP+5e712SJn0LFKR3SIzvfG4dFRgfi/VHPo/MO+4tLj2tfCm/fmtFn5gq81bQEWxdo159AwRqcZqiD9eZat6lHZBNydx6+90QA2sSawXeW+L/rXxPzRVQdf60bbgHGqRIKfQYwQ=
  file: build/distributions/xmlcalabash1-rdf-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
