language: java
script: gradle dist

# Hack dummy values into the gradle properties
install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oIGezVmuZGFuac0srrcYvBit8UzqO1q6gvZdWK1CJ4gv5E5jiUO8rUTk9H8K5jX86GMe3iqqigxzf9vL+TW0ZhtXfsKU7riHhv1sojh0y6iC8w2F9Qx8/5T98S8pRUqQ1jqSDRkLjhXz2VsANhQ3tCGOlQAIK3ac6eH71MC4YAM=
  file:
    - build/distributions/xmlcalabash1-rdf-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true

