language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: TmYjwk5BdZSyxsLOReNIo00AhQc0mRCQReNb3/CmC0zyjUD3DP9dGqSM8BKJ9De8foOEKDGkXRSsKoR0foQ5a/+so7GFdeNPd0mY/+DdYKTBzkfMXxSaFT23JIvUQA+cbPLacistxDqs2X345OPaDK6vk7VO+cTQ+dRomOHjiBI=
  skip_cleanup: true
  file:
    - build/distributions/xmlcalabash1-rdf-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
